version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  hello_world:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

  #create infrastructure job
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file infra.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - hello_world
      - create_infrastructure
