---
- name: "update packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "upgrade packages"
  become: yes
  apt:
    autoremove: yes

- name: "install node"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create web"
  file:
    path: ~/web
    state: directory

- name: "create web"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "run node"
  become: true
  shell: |
    pm2 start ~/web/index.js -f
